version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_pedidos
      MYSQL_USER: acelera
      MYSQL_PASSWORD: programador
    volumes:
      - mysql_data:/var/lib/mysql #
    restart: always

volumes:
  mysql_data: